# ----------------------------------------------------------------------------------#
#                                                                                   #
#   Copyright (C) 2025 Romulus Licensed under the MIT License.                      #
#   Developer Contact    olariu_romeo@yahoo.it                                      #
#                                                                                   #
# ----------------------------------------------------------------------------------#

#   STACK NETWORK    ---------------------------------------------------------------#

networks:                                                                           #

  #   Private network for application services    ----------------------------------#

  kabballa_private_network:
    #
    #   SSH command to create the Docker network: 
    #   docker network create --driver bridge kabballa_private_network --subnet=172.16.0.0/16
    #

    external: true

  #   Private network for mcrouter services    ------------------------------------#

  mcrouter_private_network:
    #
    #   Setup Network Driver in .env or use default bridge
    #

    driver: bridge
    external: false

  #   Private network for dragonfly services    ------------------------------------#

  dragonfly_private_network:
    #
    #   Setup Network Driver in .env or use default bridge
    #

    driver: bridge
    external: false

# ----------------------------------------------------------------------------------#

#   STACK SERVICES    --------------------------------------------------------------#

services:

  # --------------------------------------------------------------------------------#

  #   MASTER NODE 1   --------------------------------------------------------------#

  dragonfly_master1:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: dragonflydb-cluster.${DRAGONFLYDB_MASTER1_HOSTNAME:-dragonfly_master1}
    hostname: ${DRAGONFLYDB_HOSTNAME:-localhost}
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      #
      #   Set memory lock limits on .env or use value for memlock is set to -1 for auto-adjustment
      #

      memlock: ${DRAGONFLYDB_MEMLOCK:-4294967296}

    ports:
      #
      #   Expose the master node port
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11214:11211"

    volumes:
      #
      #   Config for master
      #

      - ../config/dragonfly_master1_config.json:/etc/dragonfly/dragonfly_config.json

      #
      #   Volume for master data
      #

      - dragonfly_master1_data:/data

    command:
      #
      #   Command to startr= dragonfly and set the Memcache port
      #

      - "dragonfly"
      - "--memcached_port"
      - "11211"

      #
      #   Command to setup cluster mode
      #

      - "--cluster_mode"
      - "yes"

      #
      #   Use the environment variable for setup cron
      #

      - "--snapshot_cron=${SNAPSHOT_CRON:-*/5 * * * *}"

    networks:
      #
      #   Connect to the private networks
      #

      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Add extra service entries for internal resolution
      #

      - "${DRAGONFLYDB_MASTER1_HOSTNAME:-dragonfly_master1}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"


  # ------------------------------------------------------------------------------#

  #   MASTER NODE 2    -----------------------------------------------------------#

  dragonfly_master2:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: dragonflydb-cluster.${DRAGONFLYDB_MASTER2_HOSTNAME:-dragonfly_master2}
    hostname: ${DRAGONFLYDB_HOSTNAME:-localhost}
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      #
      #   Set memory lock limits on .env or use value for memlock is set to -1 for auto-adjustment
      #

      memlock: ${DRAGONFLYDB_MEMLOCK:-4294967296} 

    ports:
      #
      #   Expose the master node port
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11215:11211"

    volumes:
      #
      #   Config for master
      #

      - ../config/dragonfly_master2_config.json:/etc/dragonfly/dragonfly_config.json

      #
      #   Volume for master data
      #

      - dragonfly_master2_data:/data

    command:
      #
      #   Command to startr= dragonfly and set the Memcache port
      #

      - "dragonfly"
      - "--memcached_port"
      - "11211"

      #
      #   Command to setup cluster mode
      #

      - "--cluster_mode"
      - "yes"

      #
      #   Use the environment variable for setup cron
      #

      - "--snapshot_cron=${SNAPSHOT_CRON:-*/5 * * * *}"

    networks:
      #
      #   Connect to the private networks
      #

      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Add extra service entries for internal resolution
      #

      - "${DRAGONFLYDB_MASTER2_HOSTNAME:-dragonfly_master2}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"


  # ------------------------------------------------------------------------------#

  #   MASTER NODE 3    -----------------------------------------------------------#

  dragonfly_master3:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: dragonflydb-cluster.${DRAGONFLYDB_MASTER3_HOSTNAME:-dragonfly_master3}
    hostname: ${DRAGONFLYDB_HOSTNAME:-localhost}
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      #
      #   Set memory lock limits on .env or use value for memlock is set to -1 for auto-adjustment
      #

      memlock: ${DRAGONFLYDB_MEMLOCK:-4294967296} 

    ports:
      #
      #   Expose the master node port
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11216:11211"

    volumes:
      #
      #   Config for master
      #

      - ../config/dragonfly_master3_config.json:/etc/dragonfly/dragonfly_config.json

      #
      #   Volume for master data
      #

      - dragonfly_master3_data:/data

    command:
      #
      #   Command to startr= dragonfly and set the Memcache port
      #

      - "dragonfly"
      - "--memcached_port"
      - "11211"

      #
      #   Command to setup cluster mode
      #

      - "--cluster_mode"
      - "yes"

      #
      #   Use the environment variable for setup cron
      #

      - "--snapshot_cron=${SNAPSHOT_CRON:-*/5 * * * *}"

    networks:
      #
      #   Connect to the private networks
      #

      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Add extra service entries for internal resolution
      #

      - "${DRAGONFLYDB_MASTER3_HOSTNAME:-dragonfly_master}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"


  # ------------------------------------------------------------------------------#

  #   SLAVE NODE 1    ------------------------------------------------------------#

  dragonfly_slave1:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: dragonflydb-cluster.${DRAGONFLYDB_SLAVE1_HOSTNAME:-dragonfly_slave1}
    hostname: ${DRAGONFLYDB_HOSTNAME:-localhost}
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      #
      #   Set memory lock limits on .env or use value for memlock is set to -1 for auto-adjustment
      #

      memlock: ${DRAGONFLYDB_MEMLOCK:-4294967296} 

    ports:
      #
      #   Expose the slave node port
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11217:11211"

    volumes:
      #
      #   Volume for slave data
      #

      - dragonfly_slave1_data:/data

      #
      #   Slave config
      #

      - ../config/dragonfly_slave1_config.json:/etc/dragonfly/dragonfly_config.json

    command: 
      #
      #   Command to startr= dragonfly and set the Memcache port
      #

      - "dragonfly"
      - "--memcached_port"
      - "11211"

      #
      #   Command to setup cluster mode
      #

      - "--cluster_mode"
      - "yes"

      #
      #   Use the environment variable for setup cron
      #

      - "--snapshot_cron=${SNAPSHOT_CRON:-*/5 * * * *}"

      #
      #   Command to setup slave and link to master
      #

      - "--replicaof"
      - "dragonfly_master1:11214"

    networks:
      #
      #   Connect to the private networks
      #

      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Add extra service entries for internal resolution
      #

      - "${DRAGONFLYDB_SLAVE1_HOSTNAME:-dragonfly_slave1}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"

    depends_on:
      dragonfly_master1:
        condition: service_healthy


  # ------------------------------------------------------------------------------#

  #   SLAVE NODE 2    ------------------------------------------------------------#

  dragonfly_slave2:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: dragonflydb-cluster.${DRAGONFLYDB_SLAVE2_HOSTNAME:-dragonfly_slave2}
    hostname: ${DRAGONFLYDB_HOSTNAME:-localhost}
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      #
      #   Set memory lock limits on .env or use value for memlock is set to -1 for auto-adjustment
      #

      memlock: ${DRAGONFLYDB_MEMLOCK:-4294967296} 

    ports:
      #
      #   Expose the slave node port
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11218:11211"

    volumes:
      #
      #   Volume for slave data
      #

      - dragonfly_slave2_data:/data

      #
      #   Slave config
      #

      - ../config/dragonfly_slave2_config.json:/etc/dragonfly/dragonfly_config.json

    command: 
      #
      #   Command to startr= dragonfly and set the Memcache port
      #

      - "dragonfly"
      - "--memcached_port"
      - "11211"

      #
      #   Command to setup cluster mode
      #

      - "--cluster_mode"
      - "yes"

      #
      #   Use the environment variable for setup cron
      #

      - "--snapshot_cron=${SNAPSHOT_CRON:-*/5 * * * *}"

      #
      #   Command to setup slave and link to master
      #

      - "--replicaof"
      - "dragonfly_master2:11215"

    networks:
      #
      #   Connect to the private networks
      #

      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Add extra service entries for internal resolution
      #

      - "${DRAGONFLYDB_SLAVE2_HOSTNAME:-dragonfly_slave2}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"

    depends_on:
      dragonfly_master2:
        condition: service_healthy


  # ------------------------------------------------------------------------------#

  #   SLAVE NODE 3    ------------------------------------------------------------#

  dragonfly_slave3:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: dragonflydb-cluster.${DRAGONFLYDB_SLAVE3_HOSTNAME:-dragonfly_slave3}
    hostname: ${DRAGONFLYDB_HOSTNAME:-localhost}
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      #
      #   Set memory lock limits on .env or use value for memlock is set to -1 for auto-adjustment
      #

      memlock: ${DRAGONFLYDB_MEMLOCK:-4294967296} 

    ports:
      #
      #   Expose the slave node port
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11219:11211"

    volumes:
      #
      #   Volume for slave data
      #

      - dragonfly_slave3_data:/data

      #
      #   Slave config
      #

      - ../config/dragonfly_slave3_config.json:/etc/dragonfly/dragonfly_config.json

    command: 
      #
      #   Command to startr= dragonfly and set the Memcache port
      #

      - "dragonfly"
      - "--memcached_port"
      - "11211"

      #
      #   Command to setup cluster mode
      #

      - "--cluster_mode"
      - "yes"

      #
      #   Use the environment variable for setup cron
      #

      - "--snapshot_cron=${SNAPSHOT_CRON:-*/5 * * * *}"

      #
      #   Command to setup slave and link to master
      #

      - "--replicaof"
      - "dragonfly_master3:11216"

    networks:
      #
      #   Connect to the private networks
      #

      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Add extra service entries for internal resolution
      #

      - "${DRAGONFLYDB_SLAVE3_HOSTNAME:-dragonfly_slave3}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"

    depends_on:
      dragonfly_master3:
        condition: service_healthy


  # ------------------------------------------------------------------------------#

  #   MCROUTER 1    --------------------------------------------------------------#

  mcrouter1:
    image: coozila/mcrouter:${MCROUTER_VERSION:-40.0.0}
    container_name: dragonflydb-cluster.${MCROUTER1_HOSTNAME:-mcrouter1}.${MCROUTER_VERSION:-40.0.0}
    hostname: ${MCROUTER_HOSTNAME:-localhost}
    platform: linux/amd64
    links:
      #
      #   Links to DragonflyDB instances
      #

      - ${DRAGONFLYDB_MASTER1_HOSTNAME:-dragonfly_master1}
      - ${DRAGONFLYDB_MASTER2_HOSTNAME:-dragonfly_master2}
      - ${DRAGONFLYDB_MASTER3_HOSTNAME:-dragonfly_master3}
      - ${DRAGONFLYDB_SLAVE1_HOSTNAME:-dragonfly_slave1}
      - ${DRAGONFLYDB_SLAVE2_HOSTNAME:-dragonfly_slave2}
      - ${DRAGONFLYDB_SLAVE3_HOSTNAME:-dragonfly_slave3}

    volumes:

      #
      #   Bind Pools: Edit .env file to change the pool variant or use the default 3pool
      #

      - ../config/mcrouter_${MCROUTER_POOL_VARIANT:-2LoadBalancerPooll+1FailoverPool}_3master_3slave.json:/etc/mcrouter/mcrouter_config.json

    command: mcrouter --config-file=/etc/mcrouter/mcrouter_config.json -p 11211
    ports:
      #
      #   Port mapping for Mcrouter
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11211:11211"

    networks:
      #
      #   Connect to the private networks
      #

      - kabballa_private_network
      - mcrouter_private_network
      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Setup MCROUTER1_HOSTNAME variable in .env file
      #

      - "${MCROUTER1_HOSTNAME:-mcrouter1}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"


  # ------------------------------------------------------------------------------#

  #   MCROUTER 2    --------------------------------------------------------------#

  mcrouter2:
    image: coozila/mcrouter:${MCROUTER_VERSION:-40.0.0}
    container_name: dragonflydb-cluster.${MCROUTER2_HOSTNAME:-mcrouter2}.${MCROUTER_VERSION:-40.0.0}
    hostname: ${MCROUTER_HOSTNAME:-localhost}
    platform: linux/amd64
    links:
      #
      #   Links to DragonflyDB instances
      #

      - ${DRAGONFLYDB_MASTER1_HOSTNAME:-dragonfly_master1}
      - ${DRAGONFLYDB_MASTER2_HOSTNAME:-dragonfly_master2}
      - ${DRAGONFLYDB_MASTER3_HOSTNAME:-dragonfly_master3}
      - ${DRAGONFLYDB_SLAVE1_HOSTNAME:-dragonfly_slave1}
      - ${DRAGONFLYDB_SLAVE2_HOSTNAME:-dragonfly_slave2}
      - ${DRAGONFLYDB_SLAVE3_HOSTNAME:-dragonfly_slave3}

    volumes:

      #
      #   Bind Pools: Edit .env file to change the pool variant or use the default 3pool
      #

      - ../config/mcrouter_${MCROUTER_POOL_VARIANT:-2LoadBalancerPooll+1FailoverPool}_3master_3slave.json:/etc/mcrouter/mcrouter_config.json

    command: mcrouter --config-file=/etc/mcrouter/mcrouter_config.json -p 11211
    ports:
      #
      #   Port mapping for Mcrouter
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11212:11211"

    networks:
      #
      #   Connect to the private networks
      #

      - kabballa_private_network
      - mcrouter_private_network
      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Setup MCROUTER3_HOSTNAME variable in .env file
      #

      - "${MCROUTER2_HOSTNAME:-mcrouter2}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"

  # ------------------------------------------------------------------------------#

  #   MCROUTER 3    --------------------------------------------------------------#

  mcrouter3:
    image: coozila/mcrouter:${MCROUTER_VERSION:-40.0.0}
    container_name: dragonflydb-cluster.${MCROUTER3_HOSTNAME:-mcrouter3}.${MCROUTER_VERSION:-40.0.0}
    hostname: ${MCROUTER_HOSTNAME:-localhost}
    platform: linux/amd64
    links:
      #
      #   Links to DragonflyDB instances
      #

      - ${DRAGONFLYDB_MASTER1_HOSTNAME:-dragonfly_master1}
      - ${DRAGONFLYDB_MASTER2_HOSTNAME:-dragonfly_master2}
      - ${DRAGONFLYDB_MASTER3_HOSTNAME:-dragonfly_master3}
      - ${DRAGONFLYDB_SLAVE1_HOSTNAME:-dragonfly_slave1}
      - ${DRAGONFLYDB_SLAVE2_HOSTNAME:-dragonfly_slave2}
      - ${DRAGONFLYDB_SLAVE3_HOSTNAME:-dragonfly_slave3}

    volumes:

      #
      #   Bind Pools: Edit .env file to change the pool variant or use the default 3pool
      #

      - ../config/mcrouter_${MCROUTER_POOL_VARIANT:-2LoadBalancerPooll+1FailoverPool}_3master_3slave.json:/etc/mcrouter/mcrouter_config.json

    command: mcrouter --config-file=/etc/mcrouter/mcrouter_config.json -p 11211
    ports:
      #
      #   Port mapping for Mcrouter
      #

      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:11213:11211"

    networks:
      #
      #   Connect to the private networks
      #

      - kabballa_private_network
      - mcrouter_private_network
      - dragonfly_private_network

    extra_hosts:
      #
      #   Add extra host entries for internal resolution
      #

      - "host.docker.internal:host-gateway"
      - "${LOCAL_LISTEN_ADDR:-127.0.0.1}:host-gateway"

      #
      #   Setup MCROUTER3_HOSTNAME variable in .env file
      #

      - "${MCROUTER3_HOSTNAME:-mcrouter3}:${LOCAL_LISTEN_ADDR:-127.0.0.1}"

# ----------------------------------------------------------------------------------#

#   STACK VOLUMES  -----------------------------------------------------------------#

volumes:

    #
    #   STACK DRAGONFLY MASTER DATA STORAGE
    #

    dragonfly_master1_data:
        driver: local

    #
    #   STACK DRAGONFLY MASTER DATA STORAGE
    #

    dragonfly_master2_data:
        driver: local

    #
    #   STACK DRAGONFLY MASTER DATA STORAGE
    #

    dragonfly_master3_data:
        driver: local

    #
    #   STACK DRAGONFLY SLAVE 1 DATA STORAGE
    #

    dragonfly_slave1_data:
        driver: local

    #
    #   STACK DRAGONFLY SLAVE 2 DATA STORAGE
    #

    dragonfly_slave2_data:
        driver: local

    #
    #   STACK DRAGONFLY SLAVE 3 DATA STORAGE
    #

    dragonfly_slave3_data:
        driver: local


# ----------------------------------------------------------------------------------#

